vpc_name                   = "vpc-dev-tech"
cluster_name               = "dev-tech-challange"
vpc_cidr                   = "10.0.0.0/16"
cluster_version            = "1.30"
ami_type                   = "AL2023_x86_64_STANDARD"
instance_types             = ["t3.medium", "t3a.medium"]
min_size                   = 1
max_size                   = 3
desired_size               = 1
metrics_server_version     = "3.12.1"
kube_state_metrics_version = "5.25.1"
ecr_repository_name        = "dev-tech-challange"
# prometheus_stack_versions  = "62.7.0"
# cert_manager_version       = "1.15.3"
