name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      destroy:
        type: boolean
        required: false
        default: false
      aws-assume-role-arn:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "us-east-1"
      environment:
        type: string
        required: true        
      

jobs:
  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        # with:
        #   path: ./terraform
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHub_AWS_OIDC
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-assume-role-arn }}      

      - name: Terraform Init
        id: init  
        run: terraform init -backend-config="./envs/${{ inputs.environment }}/backend.conf"
        continue-on-error: false

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true        

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: true 

      - name: Terraform Destroy
        if: ${{ inputs.destroy == true }}
        id: destroy
        run: terraform plan -destroy

      - name: Terraform Plan
        if: ${{ inputs.destroy != true && github.event_name == 'pull_request'}}
        id: plan
        run: terraform plan -out plan.tf -no-color     

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `### Terraform Plan ⚙️\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Resouces List
        uses: borchero/terraform-plan-comment@v2
        if: github.event_name == 'pull_request'
        with:
          token: ${{ github.token }}
          planfile: plan.tf
          working-directory: ./terraform

      - name: Terraform Apply
        if: ${{ inputs.destroy != true && github.event_name == 'push'}} 
        id: apply
        run: terraform apply plan.tf