name: "Infra Developer"

on:
  push:
    branches:
    - developer
    paths:
    - terraform/**
  pull_request:
    branches:
    - developer
    paths:
    - terraform/**

env:
  TF_WORKSPACE: "dev"
  aws-region: "us-east-1"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/action.yaml
        with:          
          aws-assume-role-arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
          environment: "dev"

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `### Terraform Plan ⚙️\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  
      - name: Terraform Resouces List
        uses: borchero/terraform-plan-comment@v2
        if: github.event_name == 'pull_request'
        with:
          token: ${{ github.token }}
          planfile: plan.tf
          working-directory: ./terraform
      
